sudo: required
dist: trusty
language: c
compiler:
  - gcc
install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-6
  - sudo apt-get install -y -qq valgrind
  - export CC=gcc-6
  - export NM=gcc-nm-6
  - export RANLIB=gcc-ranlib-6
  - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar -xvf cmocka-1.1.0.tar.xz
  - cd cmocka-1.1.0
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
  - make
  - sudo make install
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - cd ${TRAVIS_BUILD_DIR}
  - wget https://github.com/fredrikwidlund/libdynamic/releases/download/v1.0.0/libdynamic-1.0.0.tar.gz
  - tar -xvf libdynamic-1.0.0.tar.gz
  - cd libdynamic-1.0.0
  - ./configure
  - sudo make install

branches:
  only:
  - master

script:
  - cd ${TRAVIS_BUILD_DIR}
  - export CC=gcc-6
  - export NM=gcc-nm-6
  - export RANLIB=gcc-ranlib-6
  - ./autogen.sh && ./configure && make check

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
